#ifndef TERMINALGLOBALS_H
#define TERMINALGLOBALS_H

const float TERMINAL_X_START = 15;
const float BOTTOM_WINDOW_OFFSET = 110;
const float TERMINAL_INIT_X_OFFSET = 35;
const float UNDERSCORE_Y_OFFSET = 3;
const float TEXT_OFFSET = 20;
const float TERMINAL_Y_LINE_SPACING = 3;
const float TERMINAL_LINE_VERTICAL_OFFSET = TERMINAL_MONACO_HEIGHT_LINE_OF_TEXT + TERMINAL_Y_LINE_SPACING;

#endif //TERMINALGLOBALS_H
