#ifndef TEXTBASED_RENDERSTYLE_H
#define TEXTBASED_RENDERSTYLE_H


enum class RenderStyle{
    WHITE_MONACO_GENERIC,
    WHITE_TERMINAL,
    GRAY_TERMINAL,
    GREEN_TERMINAL,
    AMBER_TERMINAL,
    GRAY_LETTER,
    GREEN_LETTER_IN_BANK,
    WHITE_LETTER_IN_BANK,
    TINY_GREEN_NUMBER,
    TINY_WHITE_NUMBER,
    RED,
    GOLD
//    LETTER,
//    TERMINAL,
//    ENGINEER_TERMINAL,
//    OLD_TERMINAL_COMMAND,
//    UNUSED_TINY_NUMBER,
//    UNUSED_LETTER_BANK,
//    USED_TINY_NUMBER,
//    USED_LETTER_BANK
};

#endif //TEXTBASED_RENDERSTYLE_H
